FROM acr-on-enterprise-registry.cn-hangzhou.cr.aliyuncs.com/on-common/node:18.18.2

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

EXPOSE 10001

CMD [ "node", "dist/server/auth.js" ]
# CMD [ "npm", "run", "start:auth" ]
# CMD ["tail", "-f", "/dev/null"]
